// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-rs4RcGK8ZIiqf0FeZjquA9VBWFuDh0',
    appId: '1:673014775519:web:3347edc11ff971f8d2336a',
    messagingSenderId: '673014775519',
    projectId: 'journal-trend-3a6d8',
    authDomain: 'journal-trend-3a6d8.firebaseapp.com',
    storageBucket: 'journal-trend-3a6d8.firebasestorage.app',
    measurementId: 'G-9QB4BCDT6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVkTfDdHnvJNKSRD6PLTuQwc5pQcNzzo',
    appId: '1:673014775519:android:f70aaa64439fd6c2d2336a',
    messagingSenderId: '673014775519',
    projectId: 'journal-trend-3a6d8',
    storageBucket: 'journal-trend-3a6d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbD92ch4iCMKEapVDrWEN6BdrcHzN55c',
    appId: '1:673014775519:ios:373fb0a5dc0c04ced2336a',
    messagingSenderId: '673014775519',
    projectId: 'journal-trend-3a6d8',
    storageBucket: 'journal-trend-3a6d8.firebasestorage.app',
    iosBundleId: 'com.example.scientificJournalTrendTrackerFrontendFlutterApp',
  );
}
